from __future__ import annotations

import hashlib
import json
import re
import threading
import time
from dataclasses import dataclass
from typing import cast

import duckdb
import pandas as pd
from sqlalchemy.orm import Session
from sqlglot import expressions as exp
from sqlglot import parse
from sqlglot.errors import ParseError

from app.core.config import settings
from app.db.models import Chart, Dataset, GeneratedSQLQuery, SQLExecutionResult
from app.services.llm import LLMProviderError, chat_completion, extract_json_object, openai_enabled

BLOCKED = {
    "drop",
    "delete",
    "update",
    "insert",
    "alter",
    "create",
    "copy",
    "attach",
    "install",
    "load",
    "pragma",
    "read_csv",
    "read_parquet",
    "httpfs",
}
SENSITIVE_PATTERNS = {"email", "phone", "ssn", "password", "token", "secret", "credit_card"}


@dataclass
class SafetyResult:
    status: str
    findings: list[str]
    validated_sql: str | None


class SQLSafetyError(ValueError):
    def __init__(self, findings: list[str]) -> None:
        super().__init__("SQL failed safety validation")
        self.findings = findings


def sql_fingerprint(sql: str) -> str:
    return hashlib.sha256(sql.encode("utf-8")).hexdigest()


def dataset_fingerprint(dataset: Dataset) -> str:
    payload = {
        "id": str(dataset.id),
        "content_hash": dataset.content_hash,
        "table": dataset.duckdb_table_name,
        "rows": dataset.row_count,
        "columns": sorted((c.column_name, c.inferred_type) for c in dataset.columns),
    }
    return hashlib.sha256(json.dumps(payload, separators=(",", ":"), sort_keys=True).encode()).hexdigest()


def classify_intent(question: str) -> str:
    q = question.lower()
    if "forecast" in q or "next" in q and "month" in q:
        return "forecasting"
    if "risk" in q or "predict" in q or "at risk" in q:
        return "modeling"
    if "why" in q or "driver" in q or "eda" in q:
        return "eda"
    return "sql_analytics"


def generate_sql(question: str, dataset: Dataset) -> tuple[str, str]:
    table = dataset.duckdb_table_name
    if not table:
        raise ValueError("Dataset is not loaded into DuckDB")
    columns = [c.column_name for c in dataset.columns]
    if openai_enabled(settings.sql_generator_provider):
        try:
            schema = ", ".join(columns)
            content = chat_completion(
                system=(
                    "You generate conservative DuckDB SQL for enterprise analytics. "
                    "Return only JSON with keys sql and explanation. Generate one read-only "
                    "SELECT or WITH query. Never use DDL, DML, external file access, PRAGMA, "
                    "COPY, INSTALL, LOAD, ATTACH, or multiple statements. Always include LIMIT."
                ),
                user=(
                    f"Table name: {table}\nColumns: {schema}\n"
                    f"Business question: {question}\n"
                    "Use only listed columns and avoid sensitive columns."
                ),
                json_mode=True,
            )
            parsed = extract_json_object(content)
            return str(parsed["sql"]).strip(), str(parsed.get("explanation", "Generated by OpenAI-compatible provider."))
        except (KeyError, TypeError, ValueError, LLMProviderError):
            # Safety-first fallback keeps local demos working if provider output is malformed.
            pass
    q = question.lower()
    if "segment" in q and "churn" in q:
        sql = f"SELECT customer_segment, AVG(churned) AS churn_rate, COUNT(*) AS customers FROM {table} GROUP BY customer_segment ORDER BY churn_rate DESC LIMIT 25"
    elif "region" in q and "churn" in q:
        sql = f"SELECT region, AVG(churned) AS churn_rate, COUNT(*) AS customers FROM {table} GROUP BY region ORDER BY churn_rate DESC LIMIT 25"
    elif "revenue" in q and "plan" in q:
        sql = f"SELECT plan_type, SUM(total_revenue) AS total_revenue, AVG(monthly_revenue) AS avg_monthly_revenue FROM {table} GROUP BY plan_type ORDER BY total_revenue DESC LIMIT 25"
    elif "risk" in q or "at risk" in q:
        sql = f"SELECT customer_id, customer_segment, monthly_revenue, support_tickets, payment_failures, usage_minutes FROM {table} WHERE churned = 0 ORDER BY payment_failures DESC, support_tickets DESC, usage_minutes ASC LIMIT 50"
    else:
        sql = f"SELECT customer_id, customer_segment, plan_type, monthly_revenue, total_revenue FROM {table} LIMIT 50"
    return sql, "Generated by deterministic local provider using the dataset schema and business intent."


def validate_sql(sql: str, dataset: Dataset, allowed_columns: set[str] | None = None) -> SafetyResult:
    table = dataset.duckdb_table_name
    if not table:
        return SafetyResult("blocked", ["Dataset is not loaded into DuckDB"], None)
    stripped = sql.strip().rstrip(";")
    findings: list[str] = []
    if ";" in stripped:
        findings.append("Multiple SQL statements are blocked")
    parsed: exp.Expression | None = None
    try:
        parsed_statements = parse(stripped, read="duckdb")
        if len(parsed_statements) != 1:
            findings.append("Exactly one SQL statement is allowed")
        elif parsed_statements:
            parsed = cast(exp.Expression, parsed_statements[0])
    except ParseError as exc:
        findings.append(f"SQL parser rejected query: {exc.errors[0].get('description', str(exc)) if exc.errors else str(exc)}")
    tokens = set(re.findall(r"[a-zA-Z_][a-zA-Z0-9_]*", stripped.lower()))
    blocked_tokens = sorted(tokens & BLOCKED)
    if blocked_tokens:
        findings.append(f"Blocked SQL tokens: {', '.join(blocked_tokens)}")
    if parsed is not None and not isinstance(parsed, exp.Select):
        findings.append("Only SELECT or WITH queries are allowed")
    elif parsed is None and not re.match(r"^\s*(select|with)\b", stripped, re.IGNORECASE | re.DOTALL):
        findings.append("Only SELECT or WITH queries are allowed")
    if parsed is not None:
        cte_names = {cte.alias_or_name.lower() for cte in parsed.find_all(exp.CTE)}
        physical_tables: set[str] = set()
        for table_expr in parsed.find_all(exp.Table):
            name = table_expr.name.lower()
            if name in cte_names:
                continue
            physical_tables.add(name)
            if table_expr.catalog or table_expr.db:
                findings.append("Catalog- and schema-qualified table access is blocked")
        if physical_tables != {table.lower()}:
            unexpected = sorted(physical_tables - {table.lower()})
            if unexpected:
                findings.append(f"Unapproved dataset tables: {', '.join(unexpected)}")
            if table.lower() not in physical_tables:
                findings.append("SQL must reference the selected dataset table")
    elif table not in stripped:
        findings.append("SQL must reference the selected dataset table")
    selected_all = bool(parsed and list(parsed.find_all(exp.Star))) or bool(
        re.search(r"\bselect\s+(\*|[a-zA-Z_][a-zA-Z0-9_]*\.\*)", stripped, re.IGNORECASE)
    )
    sensitive_in_schema = sorted(
        [
            c
            for c in (allowed_columns or set())
            if any(pattern in c.lower() for pattern in SENSITIVE_PATTERNS)
        ]
    )
    if selected_all and sensitive_in_schema:
        findings.append("SELECT * is blocked because the dataset contains sensitive columns")
    if any(pattern in token for token in tokens for pattern in SENSITIVE_PATTERNS):
        findings.append("Sensitive columns require explicit governance review and are blocked in analytics SQL")
    if allowed_columns:
        allowed_lower = {c.lower() for c in allowed_columns}
        if parsed is not None:
            aliases = {alias.alias.lower() for alias in parsed.find_all(exp.Alias) if alias.alias}
            columns = {column.name.lower() for column in parsed.find_all(exp.Column)}
            unknown = sorted([column for column in columns if column not in allowed_lower and column not in aliases])
            if unknown:
                findings.append(f"Unknown columns or identifiers: {', '.join(unknown[:8])}")
        else:
            aliases = {a.lower() for a in re.findall(r"\bas\s+([a-zA-Z_][a-zA-Z0-9_]*)", stripped, re.IGNORECASE)}
            cte_names = {
                c.lower()
                for c in re.findall(
                    r"(?:with|,)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s+as\s*\(",
                    stripped,
                    re.IGNORECASE,
                )
            }
            safe_words = {
                "select", "from", "where", "group", "by", "order", "limit", "as", "avg", "sum", "count",
                "min", "max", "cast", "double", "int", "integer", "float", "decimal", "nullif", "coalesce",
                "case", "when", "then", "else", "end", "true", "false", "desc", "asc", "and", "or", "with",
            }
            identifiers = tokens - BLOCKED - safe_words - aliases - cte_names
            unknown = sorted(
                [i for i in identifiers if i != table.lower() and i not in {c.lower() for c in allowed_columns}]
            )
            if unknown:
                findings.append(f"Unknown columns or identifiers: {', '.join(unknown[:8])}")
    if "limit" not in tokens:
        stripped = f"{stripped} LIMIT 100"
    return SafetyResult("blocked" if findings else "safe", findings, None if findings else stripped)


def bind_approval(query: GeneratedSQLQuery, dataset: Dataset) -> None:
    safety = validate_sql(query.validated_sql or query.generated_sql, dataset, {c.column_name for c in dataset.columns})
    if safety.status != "safe" or not safety.validated_sql:
        raise SQLSafetyError(safety.findings)
    query.validated_sql = safety.validated_sql
    query.approved_sql_hash = sql_fingerprint(safety.validated_sql)
    query.approved_dataset_fingerprint = dataset_fingerprint(dataset)
    query.approval_status = "approved"


def _cell_size(value: object) -> int:
    if value is None:
        return 1
    if isinstance(value, bytes):
        return len(value)
    return len(str(value).encode("utf-8"))


def execute_query(db: Session, query: GeneratedSQLQuery, dataset: Dataset) -> SQLExecutionResult:
    safety = validate_sql(query.validated_sql or query.generated_sql, dataset, {c.column_name for c in dataset.columns})
    if safety.status != "safe" or not safety.validated_sql:
        query.safety_status = "blocked"
        query.safety_findings = safety.findings
        query.execution_status = "blocked"
        raise SQLSafetyError(safety.findings)
    current_sql_hash = sql_fingerprint(safety.validated_sql)
    current_dataset_fingerprint = dataset_fingerprint(dataset)
    if (
        not query.approved_sql_hash
        or not query.approved_dataset_fingerprint
        or query.approved_sql_hash != current_sql_hash
        or query.approved_dataset_fingerprint != current_dataset_fingerprint
    ):
        query.approval_status = "revoked"
        query.execution_status = "blocked"
        raise SQLSafetyError(["Approval binding no longer matches the normalized SQL and dataset version"])
    query.validated_sql = safety.validated_sql
    start = time.monotonic()
    con = duckdb.connect(settings.duckdb_path)
    timer = threading.Timer(settings.sql_timeout_seconds, con.interrupt)
    rows: list[tuple] = []
    columns: list[str] = []
    result_bytes = 0
    try:
        con.execute("SET enable_external_access = false")
        con.execute(f"SET memory_limit = '{settings.sql_memory_limit_mb}MB'")
        timer.start()
        cursor = con.execute(f"SELECT * FROM ({safety.validated_sql}) AS _approved_query LIMIT {settings.sql_max_rows + 1}")
        columns = [item[0] for item in cursor.description]
        while batch := cursor.fetchmany(min(500, settings.sql_max_rows + 1 - len(rows))):
            for row in batch:
                result_bytes += sum(_cell_size(value) for value in row)
                if result_bytes > settings.sql_max_result_bytes:
                    raise SQLSafetyError(["Query result exceeded the byte materialization budget"])
                rows.append(row)
                if len(rows) > settings.sql_max_rows:
                    raise SQLSafetyError(["Query result exceeded the row materialization budget"])
    except duckdb.Error as exc:
        if time.monotonic() - start >= settings.sql_timeout_seconds:
            raise SQLSafetyError(["Query exceeded the execution time budget"]) from exc
        raise SQLSafetyError(["DuckDB rejected the governed query"]) from exc
    finally:
        timer.cancel()
        con.close()
    df = pd.DataFrame.from_records(rows, columns=columns)
    latency = int((time.monotonic() - start) * 1000)
    preview = df.head(100).fillna("").to_dict(orient="records")
    result = SQLExecutionResult(
        sql_query_id=query.id,
        row_count=len(df),
        columns=list(df.columns),
        result_preview=preview,
        latency_ms=latency,
    )
    db.add(result)
    query.execution_status = "executed"
    query.latency_ms = latency
    chart_spec = make_chart_spec(df, query)
    db.add(Chart(sql_query_id=query.id, chart_type=chart_spec["type"], title=chart_spec["layout"]["title"], chart_spec=chart_spec))
    return result


def make_chart_spec(df: pd.DataFrame, query: GeneratedSQLQuery) -> dict:
    if df.empty or len(df.columns) < 2:
        return {"type": "table", "data": [], "layout": {"title": "Query result"}}
    x_col = df.columns[0]
    y_candidates = [c for c in df.columns[1:] if pd.api.types.is_numeric_dtype(df[c])]
    if not y_candidates:
        return {"type": "table", "data": [], "layout": {"title": "Query result"}}
    y_col = y_candidates[0]
    return {
        "type": "bar",
        "data": [{"type": "bar", "x": df[x_col].astype(str).tolist(), "y": df[y_col].astype(float).round(4).tolist()}],
        "layout": {"title": f"{y_col} by {x_col}", "xaxis": {"title": x_col}, "yaxis": {"title": y_col}},
    }
