from __future__ import annotations

import re
import time
from dataclasses import dataclass

import duckdb
import pandas as pd
from sqlalchemy.orm import Session

from app.core.config import settings
from app.db.models import Chart, Dataset, GeneratedSQLQuery, SQLExecutionResult

BLOCKED = {
    "drop",
    "delete",
    "update",
    "insert",
    "alter",
    "create",
    "copy",
    "attach",
    "install",
    "load",
    "pragma",
    "read_csv",
    "read_parquet",
    "httpfs",
}
SENSITIVE_PATTERNS = {"email", "phone", "ssn", "password", "token", "secret", "credit_card"}


@dataclass
class SafetyResult:
    status: str
    findings: list[str]
    validated_sql: str | None


def classify_intent(question: str) -> str:
    q = question.lower()
    if "forecast" in q or "next" in q and "month" in q:
        return "forecasting"
    if "risk" in q or "predict" in q or "at risk" in q:
        return "modeling"
    if "why" in q or "driver" in q or "eda" in q:
        return "eda"
    return "sql_analytics"


def generate_sql(question: str, dataset: Dataset) -> tuple[str, str]:
    table = dataset.duckdb_table_name
    if not table:
        raise ValueError("Dataset is not loaded into DuckDB")
    q = question.lower()
    if "segment" in q and "churn" in q:
        sql = f"SELECT customer_segment, AVG(churned) AS churn_rate, COUNT(*) AS customers FROM {table} GROUP BY customer_segment ORDER BY churn_rate DESC LIMIT 25"
    elif "region" in q and "churn" in q:
        sql = f"SELECT region, AVG(churned) AS churn_rate, COUNT(*) AS customers FROM {table} GROUP BY region ORDER BY churn_rate DESC LIMIT 25"
    elif "revenue" in q and "plan" in q:
        sql = f"SELECT plan_type, SUM(total_revenue) AS total_revenue, AVG(monthly_revenue) AS avg_monthly_revenue FROM {table} GROUP BY plan_type ORDER BY total_revenue DESC LIMIT 25"
    elif "risk" in q or "at risk" in q:
        sql = f"SELECT customer_id, customer_segment, monthly_revenue, support_tickets, payment_failures, usage_minutes FROM {table} WHERE churned = 0 ORDER BY payment_failures DESC, support_tickets DESC, usage_minutes ASC LIMIT 50"
    else:
        sql = f"SELECT customer_id, customer_segment, plan_type, monthly_revenue, total_revenue FROM {table} LIMIT 50"
    return sql, "Generated by deterministic local provider using the dataset schema and business intent."


def validate_sql(sql: str, dataset: Dataset, allowed_columns: set[str] | None = None) -> SafetyResult:
    table = dataset.duckdb_table_name
    if not table:
        return SafetyResult("blocked", ["Dataset is not loaded into DuckDB"], None)
    stripped = sql.strip().rstrip(";")
    findings: list[str] = []
    if ";" in stripped:
        findings.append("Multiple SQL statements are blocked")
    tokens = set(re.findall(r"[a-zA-Z_][a-zA-Z0-9_]*", stripped.lower()))
    blocked_tokens = sorted(tokens & BLOCKED)
    if blocked_tokens:
        findings.append(f"Blocked SQL tokens: {', '.join(blocked_tokens)}")
    if not re.match(r"^\s*(select|with)\b", stripped, re.IGNORECASE | re.DOTALL):
        findings.append("Only SELECT or WITH queries are allowed")
    if table not in stripped:
        findings.append("SQL must reference the selected dataset table")
    selected_all = bool(re.search(r"\bselect\s+(\*|[a-zA-Z_][a-zA-Z0-9_]*\.\*)", stripped, re.IGNORECASE))
    sensitive_in_schema = sorted(
        [
            c
            for c in (allowed_columns or set())
            if any(pattern in c.lower() for pattern in SENSITIVE_PATTERNS)
        ]
    )
    if selected_all and sensitive_in_schema:
        findings.append("SELECT * is blocked because the dataset contains sensitive columns")
    if any(pattern in token for token in tokens for pattern in SENSITIVE_PATTERNS):
        findings.append("Sensitive columns require explicit governance review and are blocked in analytics SQL")
    if allowed_columns:
        aliases = {a.lower() for a in re.findall(r"\bas\s+([a-zA-Z_][a-zA-Z0-9_]*)", stripped, re.IGNORECASE)}
        safe_words = {
            "select",
            "from",
            "where",
            "group",
            "by",
            "order",
            "limit",
            "as",
            "avg",
            "sum",
            "count",
            "min",
            "max",
            "desc",
            "asc",
            "and",
            "or",
            "with",
        }
        identifiers = tokens - BLOCKED - safe_words - aliases
        unknown = sorted(
            [i for i in identifiers if i != table.lower() and i not in {c.lower() for c in allowed_columns}]
        )
        if unknown:
            findings.append(f"Unknown columns or identifiers: {', '.join(unknown[:8])}")
    if "limit" not in tokens:
        stripped = f"{stripped} LIMIT 100"
    return SafetyResult("blocked" if findings else "safe", findings, None if findings else stripped)


def execute_query(db: Session, query: GeneratedSQLQuery, dataset: Dataset) -> SQLExecutionResult:
    start = time.time()
    con = duckdb.connect(settings.duckdb_path)
    df = con.execute(query.validated_sql or query.generated_sql).fetchdf()
    con.close()
    latency = int((time.time() - start) * 1000)
    preview = df.head(100).fillna("").to_dict(orient="records")
    result = SQLExecutionResult(
        sql_query_id=query.id,
        row_count=len(df),
        columns=list(df.columns),
        result_preview=preview,
        latency_ms=latency,
    )
    db.add(result)
    query.execution_status = "executed"
    query.latency_ms = latency
    chart_spec = make_chart_spec(df, query)
    db.add(Chart(sql_query_id=query.id, chart_type=chart_spec["type"], title=chart_spec["layout"]["title"], chart_spec=chart_spec))
    return result


def make_chart_spec(df: pd.DataFrame, query: GeneratedSQLQuery) -> dict:
    if df.empty or len(df.columns) < 2:
        return {"type": "table", "data": [], "layout": {"title": "Query result"}}
    x_col = df.columns[0]
    y_candidates = [c for c in df.columns[1:] if pd.api.types.is_numeric_dtype(df[c])]
    if not y_candidates:
        return {"type": "table", "data": [], "layout": {"title": "Query result"}}
    y_col = y_candidates[0]
    return {
        "type": "bar",
        "data": [{"type": "bar", "x": df[x_col].astype(str).tolist(), "y": df[y_col].astype(float).round(4).tolist()}],
        "layout": {"title": f"{y_col} by {x_col}", "xaxis": {"title": x_col}, "yaxis": {"title": y_col}},
    }
